export const questionsCategories = {
  realistic: [
    'I am very authentic and say what I think.',
    `I'm shy, I think a lot before I expose myself.`,
    'Deep intellectual issues do not interest me.',
    'I am persistent and do not give up until I reach my goals.',
    'People can count on me. I am quite stable in my actions.',
    'I enjoy working with materials, hands, objects and instruments.',
    'I can handle physical or intellectual activity for a long time.',
    'I give a lot of value for money.',
    'I know how to use electronic instruments and devices.',
    'I accept the rules, limits, orders and the context in which I live.',
  ],
  investigative: [
    `I like to observe, analyze and understand the way things, nature or people work.`,
    `I'm not very impulsive, I think before I act.`,
    `Areas like math or science attract me. I like to study a subject in depth.`,
    `I find it easy to learn.`,
    `I am rational in making a decision or in deciding the best way forward.`,
    `I am very organized and detail oriented.`,
    'I am able to give precise answers about dates, values ​​and describe a certain situation in the past.',
    `I have a great critical sense. Things can always be improved.`,
    `I like to make my own decisions, even if it is different from the thinking of the majority.`,
    `I have good logical or mathematical skills.`,
  ],
  entrepreneur: [
    `I am firm and confident in my decisions and I don't need guesses.`,
    `I can often convince people of a certain point of view.`,
    `I am a motivated, self-motivated, optimistic person.`,
    `I talk too much. I don't easily give up on an argument.`,
    `I place a high value on material goods. I like to buy and sometimes even demonstrate to others my achievements, my material possessions, my wisdom and my talents.`,
    `I make decisions quickly. I act without much thought. I get to be impulsive.`,
    `I like being with people, especially to show them the way I think.`,
    `I love adventures, taking risks and challenges.`,
    `I am always looking for new opportunities, new paths to follow.`,
    `I'd rather be a business owner than work for someone else.`,
  ],
  conventional: [
    `I accept the rules and the context in which I live. I like clear boundaries.`,
    `I am an introvert, I guard myself and do not expose myself much.`,
    `I take care of my things and I like to keep them.`,
    `I am very calm and have a good emotional balance.`,
    `I prefer to have an action plan, a defined work routine.`,
    `I am a stable, reliable type of person suited to reality.`,
    `I respect ethics, I keep secrets, I comply with my agreements.`,
    `I am very organized and detailed in things. Effectiveness is very important to me.`,
    `I go all the way in my goals. I don't give up until I reach them.`,
    `I like to satisfy others in relation to what they ask of me.`,
  ],
  artistic: [
    `It is difficult for me to accept rules, limits and something imposed on me.`,
    `It is easy for me to live in a disorganized environment and do things without logic.`,
    `I'm very sensitive. I use emotion more in my decisions.`,
    `I am an idealistic person. I believe we can build a better world.`,
    `I like to create, invent, idealize and fantasize.`,
    `I like to make an impact, provoking, entertaining, seducing, enchanting people.`,
    `I like to discover new possibilities for things and situations in life.`,
    `I often don't think long before making a decision, nor do I measure the consequences.`,
    `I like to express myself, to represent myself or to show myself in public.`,
    `I am responsible for my attitudes and decisions.`,
  ],
  social: [
    `I like to lead, organize or mobilize a group around a cause or action.`,
    `I like to help and collaborate with others. I am loyal and I like to do good.`,
    `I use emotion and sensitivity to make decisions.`,
    `I am generally a pleasant and easy going person.`,
    `I am an idealist and I want more out of life.`,
    `Ethical, justice or common welfare issues are important to me.`,
    `I'm responsible. You can count on me because I always live up to expectations.`,
    `I tend to dedicate myself to people, or causes, "wearing the shirt" of a group or club that I believe in.`,
    `In general, I relate well with others. I find it easy to talk.`,
    `I like to help, teach, take care, somehow I want to be important to others.`,
  ],
}

export const answerOptions = [
  'Has nothing to do with me',
  'Has a little to do with me',
  'Has a lot to do with me',
  `That's how I am!`,
]
